// Bundles the extension: the pump worker becomes a string the page starts as a Blob worker, and everything else
// is one classic script for the manifest's MAIN-world content script. Output: extension/dist/coop-main.js
import { build } from "esbuild";
import fs from "node:fs";

const dir = new URL(".", import.meta.url).pathname;
const { version } = JSON.parse(fs.readFileSync(`${dir}manifest.json`, "utf8"));

const pump = await build({
  entryPoints: [`${dir}src/pump-worker.js`],
  bundle: true,
  format: "iife",
  target: "chrome120",
  write: false,
  minify: false,
  legalComments: "none",
});

await build({
  entryPoints: [`${dir}src/main.js`],
  bundle: true,
  format: "iife",
  target: "chrome120",
  outfile: `${dir}dist/coop-main.js`,
  legalComments: "none",
  banner: { js: `// BO1 Zombies co-op for vel.gg ${version} (generated by extension/build.mjs; edit extension/src instead)` },
  define: {
    __PUMP_SOURCE__: JSON.stringify(pump.outputFiles[0].text),
    __VERSION__: JSON.stringify(version),
  },
});
console.log(`built dist/coop-main.js (${version})`);
